### ISSUE TITLE
Feature: Default rule for PR titles that do not match any rule

### ISSUE THREAD

**Issue by patricklubach** [patricklubach/approver-action#1]
This default rule requires either zero or more approvers to be fulfilled.

Something like this:

```yaml
- regex: ^feature/
  approvers:
    - user:patricklubach
- regex: ^bugfix/
  approvers:
    - user:racoon63
- default: true
  approvers:
    - user:racoon63
```
