### ISSUE TITLE
Feature: Amount of approvals from approvers list

### ISSUE THREAD

**Issue by patricklubach** [patricklubach/approver-action#3]
In default all defined approvers need to approve the pull request. There should be a possibility to define the number of required approvals from defined list. Following a suggestion for configuration of the approvers file:

```yaml
- regex: ^feature/
  approvers:
    - user:patricklubach
    - user:racoon63
  count: 1
- regex: ^bugfix/
  approvers:
    - user:racoon63
  count: 1
- default: true
  approvers:
    - user:racoon63
```

it is necessary to check after someone approves if it is someone who is actually in the approvers file.
