### ISSUE TITLE
Check on pull request title or on pull request branch

### ISSUE THREAD

**Issue by patricklubach** [patricklubach/approver-action#41]
I want to have a global configuration to configure if I want to check on the title or the branch name. Default should be branch_name.

This introduces the `rules` key for the rules.

exemplary config:

```yaml
check_on: title

rules:
- regex: ^feature/
  count: 1
  approvers:
    - user:patricklubach
    - user:racoon63
- regex: "^build(deps|deps-dev):*"
  approvers:
    - user:patricklubach
- default: true
  approvers:
    - user:patricklubach
```
